# Generated by Django 4.2.5 on 2023-09-08 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
